site_name: Flotiq Developer Documentation
site_url: https://flotiq.com/docs/
copyright: Copyright &copy; 2019 onwards Flotiq
dev_addr: 0.0.0.0:4000
theme:
     name: 'material'
     logo: 'API/images/f.png'
     custom_dir: 'theme'
     palette:
         primary: 'teal'
     features:
       - instant
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized

extra_css:
  - 'css/flotiq.css'
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.0.1/build/styles/default.min.css
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.0.1/build/styles/nord.min.css
    #  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.min.css

google_analytics:
  - 'UA-10126793-18'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.0.1/build/highlight.min.js
  - 'js/flotiq.js'
    #- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.min.js
    #- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/mode/javascript/javascript.min.js

extra:
  disqus: 'flotiq'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/flotiq
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/flotiq
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/flotiq/

nav:
  - 'Home': index.md
  - API:
    - 'API access & scoped keys': API/index.md
    - 'Working with Content Types': API/content-types.md
    - 'Dynamic Content API': API/dynamic-content-api.md
    - 'GraphQL': API/graph-ql.md
    - 'Generating SDKs': API/generate-package.md
    - 'OpenAPI': API/open-api-schema.md
    - 'Full-text search': API/search.md
    - 'Working with media': API/media-library.md
    - 'Zapier & integrations': API/zapier.md
  - Dashboard:
    - 'Overview': panel/index.md
    - 'Content types': panel/content-types.md
    - 'Predefined Content Types': panel/predefined-content-types.md
    - 'Content objects': panel/content-objects.md
    - 'Media library': panel/media-library.md
    - Plugins:
      - 'Gatsby Cloud': panel/Plugins/Gatsby-cloud-integration.md
  - CLI:
    - 'Overview': CLI/index.md
    - 'Starting new project with Gatsby and Flotiq': CLI/starting-new-project.md
    - 'Importing data from Gatsby starter to Flotiq': CLI/importing-data.md
    - 'Migrate WordPress blog content to Flotiq': CLI/wordpress-importer.md
  - Deep dives:
    - 'Overview': Deep-Dives/index.md
    - 'Angular 9 with Flotiq SDK': Deep-Dives/angular-headless-cms.md
    - 'Building a blog': Deep-Dives/Building-a-blog-in-3-minutes.md
    - 'Building a contact form': Deep-Dives/Headless-CMS-Contact-Forms.md
    - 'Building a banner rotator': Deep-Dives/building-a-banner-rotator-with-an-admin-interface.md
    - 'Complex data structures': Deep-Dives/jamstack-recipes-website-complex-data-structures.md
    - 'Importing from Wordpress': Deep-Dives/wordpress-import.md
    - 'E-commerce with Snipcart & Gatsby': Deep-Dives/node-js-ecommerce-snipcart-gatsby-demo.md
    - 'Full-text search': Deep-Dives/search-api-deepdive.md
    - 'Securing JAMstack APIs': Deep-Dives/securing-write-api-access.md
    - 'Custom domains in Heroku': Deep-Dives/add-a-custom-domain-to-heroku-for-free.md
    - 'Use Netlify, Zapier and Gatsby to instantly deploy your Flotiq content': 'Deep-Dives/netlify-zapier-gatsby-serverless-deployment-pipeline.md'
